In [8]:
import requests
import pandas as pd

In [5]:
response = requests.get('https://api.themoviedb.org/3/movie/popular?api_key=220629820aa4e64a14880a6d84d41e42&language=en-US&page=1').json()

In [11]:
popularity =[]
vote_count = []
original_language = []
title = []
vote_average = []
overview = []
release_date = []

for i in response['results']:
    popularity.append(i['popularity'])
    vote_count.append(i['vote_count'])
    original_language.append(i['original_language'])
    title.append(i['title'])
    vote_average.append(i['vote_average'])
    overview.append(i['overview'])
    release_date.append(i['release_date'])
    
d = {'title':title, 'overview':overview, 'release_date':release_date,
         'original_language': original_language, 'popularity':popularity,
         'release_date':release_date,'vote_count':vote_count, 
         'vote_average':vote_average}
    
df = pd.DataFrame(d)

df.head()

,title,overview,release_date,original_language,popularity,vote_count,vote_average
0,Thor: Love and Thunder,After his retirement is interrupted by Gorr th...,2022-07-06,en,9386.438,1747,6.8
1,Minions: The Rise of Gru,A fanboy of a supervillain supergroup known as...,2022-06-29,en,4856.051,1163,7.8
2,Jurassic World Dominion,"Four years after Isla Nublar was destroyed, di...",2022-06-01,en,4951.784,2615,7.1
3,Top Gun: Maverick,After more than thirty years of service as one...,2022-05-24,en,4194.193,1851,8.3
4,The Black Phone,"Finney Shaw, a shy but clever 13-year-old boy,...",2022-06-22,en,3074.402,1667,8.0

### Now we need to do this for every page and append it.

In [12]:
response['total_pages']

34666

In [15]:
final = pd.DataFrame()
for j in range(1, 10):
    response = requests.get(f'https://api.themoviedb.org/3/movie/popular?api_key=220629820aa4e64a14880a6d84d41e42&language=en-US&page={j}').json()
    popularity =[]
    vote_count = []
    original_language = []
    title = []
    vote_average = []
    overview = []
    release_date = []

    for i in response['results']:
        popularity.append(i['popularity'])
        vote_count.append(i['vote_count'])
        original_language.append(i['original_language'])
        title.append(i['title'])
        vote_average.append(i['vote_average'])
        overview.append(i['overview'])
        release_date.append(i['release_date'])

    d = {'title':title, 'overview':overview, 'release_date':release_date,
             'original_language': original_language, 'popularity':popularity,
             'release_date':release_date,'vote_count':vote_count, 
             'vote_average':vote_average}

    df = pd.DataFrame(d)
    
    final = final.append(df, ignore_index=True) #index wont repeat
final

,title,overview,release_date,original_language,popularity,vote_count,vote_average
0,Thor: Love and Thunder,After his retirement is interrupted by Gorr th...,2022-07-06,en,9386.438,1747,6.8
1,Minions: The Rise of Gru,A fanboy of a supervillain supergroup known as...,2022-06-29,en,4856.051,1163,7.8
2,Jurassic World Dominion,"Four years after Isla Nublar was destroyed, di...",2022-06-01,en,4951.784,2615,7.1
3,Top Gun: Maverick,After more than thirty years of service as one...,2022-05-24,en,4194.193,1851,8.3
4,The Black Phone,"Finney Shaw, a shy but clever 13-year-old boy,...",2022-06-22,en,3074.402,1667,8.0
...,...,...,...,...,...,...,...
175,2037,19-year-old Yoon Young lives alone with her mo...,2022-06-08,ko,243.283,3,5.7
176,"Hello, Goodbye, and Everything in Between","Clare and Aidan, who after making a pact that ...",2022-07-06,en,232.491,91,6.0
177,Harry Potter and the Chamber of Secrets,"Cars fly, trees fight back, and a mysterious h...",2002-11-13,en,245.567,18554,7.7
178,Jungle Cruise,Dr. Lily Houghton enlists the aid of wisecrack...,2021-07-28,en,227.742,4495,7.5
179,The Last Warrior: Root of Evil,Peace and tranquility have set in Belogorie. T...,2021-01-01,ru,231.860,114,7.0